version: "3.5"
services:
  nats-0:
    image: nats
    ports:
      - "8222:8222"
      - "6222:6222"
      - "4222:4222"
    command: "--user lichmaker --pass 123456 --cluster_name mynats --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks: ["nats"]
  nats-1:
    ports:
      - "4223:4222"
    image: nats
    command: "--user lichmaker --pass 123456 --cluster_name mynats --cluster nats://0.0.0.0:6222 --routes=nats://lichmaker:123456@nats-0:6222"
    networks: ["nats"]
    depends_on: ["nats-0"]
  nats-2:
    ports:
      - "4224:4222"
    image: nats
    command: "--user lichmaker --pass 123456 --cluster_name mynats --cluster nats://0.0.0.0:6222 --routes=nats://lichmaker:123456@nats-0:6222"
    networks: ["nats"]
    depends_on: ["nats-0"]

networks:
  nats:
    name: nats